import { DefaultTheme } from "styled-components";
import { colors, typography, spacers, zIndices } from "./tokens";

export const lightTheme: DefaultTheme = {
    colors: {
        textIcon: {
            inverted: colors.base.white,
            neutral: {
                calmest: colors.gray[50],
                calm: colors.gray[200],
                loud: colors.gray[400],
                bold: colors.gray[900],
            },
            interact: {
                enabled: colors.gray[400],
                hover: colors.green[300],
                active: colors.green[400],
                focus: colors.green[300],
                disabled: colors.gray[200],
            },
            success: {
                calmest: colors.gray[50],
                calm: colors.gray[100],
                loud: colors.gray[300],
                bold: colors.gray[400],
            },
            critical: {
                calmest: colors.red[50],
                calm: colors.red[200],
                loud: colors.red[400],
                bold: colors.red[900],                        
            },        
        },
        bg: {   
            global: colors.base.white,
            overlay: colors.base.blackAlpha,
            transparent: colors.base.whiteAlpha,
            neutral: {
                muted: colors.base.white,
                calmest: colors.gray[50],
                calm: colors.gray[100],
                loud: colors.gray[200],
                loudest: colors.gray[400],
                bold: colors.gray[600],
            },
            interact: {
                green: {
                    enabled: colors.green[300],
                    hover: colors.green[200],
                    active: colors.green[400],
                    focus: colors.green[200],
                    disabled: colors.green[100],
                },
                gray: {
                    enabled: colors.gray[400],
                    hover: colors.gray[300],
                    active: colors.gray[500],
                    focus: colors.gray[300],
                    disabled: colors.gray[100],
                },
                lighWeight: {
                    enabled: colors.gray[50],
                    hover: colors.green[50],
                    active: colors.green[100],
                    focus: colors.green[50],
                    disabled: colors.gray[100],
                    selected: colors.base.white,
                    readOnly: colors.base.white,
                },
            },
            success: {
                calmest: colors.green[50],
                calm: colors.green[100],
                loud: colors.green[300],
                bold: colors.green[400],            
            },
            critical: {
                calmest: colors.red[50],
                calm: colors.red[200],
                loud: colors.red[400],
                loudest: colors.red[600],
                bold: colors.red[900],            
            },
        },
        border: {   
            inverted: colors.base.white,
            transparent: colors.base.whiteAlpha,
            neutral: {
                calmest: colors.gray[100],
                calm: colors.gray[100],
                loud: colors.gray[200],
            },
 
            interact: {
                enabled: colors.gray[400],
                hover: colors.green[300],
                active: colors.green[400],
                focus: colors.green[300],
                disabled: colors.gray[200],
                readOnly: colors.gray[200],
                complexComponent: colors.gray[100],
            },
            success: {
                calmest: colors.green[50],
                calm: colors.green[100],
                loud: colors.green[300],
                bold: colors.green[400],
            },        
            critical: {
                calmest: colors.red[50],
                calm: colors.red[200],
                loud: colors.red[400],
                loudest: colors.red[600],
                bold: colors.red[900],
            },        
        },
    },
    typography: {
        fontFamily: {
            heading: `"Roboto", -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'`,
            text: `"Roboto", -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'`,
            component: `"Roboto", -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'`,
            monospace: `"Roboto Slab", 'SFMono-Medium', 'SF Mono', 'Segoe UI Mono', 'Roboto Mono', 'Ubuntu Mono', Menlo, Consolas, Courier, monospace`,
        },
        fontSize: {
            heading: {
                h1: typography.fontSize.h1,
                h2: typography.fontSize.h2,
                h3: typography.fontSize.h3,
                h4: typography.fontSize.h4,
                h5: typography.fontSize.h5,
                h6: typography.fontSize.h6,        
            },
            text: {
                large: typography.fontSize.large,
                base: typography.fontSize.base,
                small: typography.fontSize.small,
                xSmall: typography.fontSize.xSmall,
                xxSmall: typography.fontSize.xxSmall,
                xxxSmall: typography.fontSize.xxxSmall,
            },
            componet: {
                base: typography.fontSize.base,
                small: typography.fontSize.small,
                xSmall: typography.fontSize.xSmall,
            },
        },
        lineHeight: {
            heading: {
                h1: typography.lineHeight.h1,
                h2: typography.lineHeight.h2,
                h3: typography.lineHeight.h3,
                h4: typography.lineHeight.h4,
                h5: typography.lineHeight.h5,
                h6: typography.lineHeight.h6,
            },
            text: {
                large: typography.lineHeight.large,
                base: typography.lineHeight.base,
                small: typography.lineHeight.small,
                xSmall: typography.lineHeight.xSmall,
                xxSmall: typography.lineHeight.xxSmall,
                xxxSmall: typography.lineHeight.xxxSmall,
            },
            componet: {
                base: typography.lineHeight.base,
                small: typography.lineHeight.small,
                xSmall: typography.lineHeight.xSmall,
            },
        },
        fontWeight: {
            light: typography.fontWeight.light,
            regular: typography.fontWeight.regular,
            medium: typography.fontWeight.medium,
            semibold: typography.fontWeight.semiBold,
            bold: typography.fontWeight.bold,
            lightItalic: typography.fontWeight.lightItalic,
            italic: typography.fontWeight.italic,
        },
    },
    spacing: {
        paddings: {
            noPaddings: spacers[0],
            xxxxxCompact: spacers[2],
            xxxxCompact: spacers[4],
            xxxCompact: spacers[6],
            xxCompact: spacers[8],
            xCompact: spacers[10],
            compact: spacers[12],
            default: spacers[16],
            relaxed: spacers[24],
            large: spacers[32],
            section: spacers[48],
        },
        inner: {
            noGap: spacers[0],
            closest: spacers[2],
            close: spacers[4],
            related: spacers[8],
            grouped: spacers[16],
        },
        outer: {
            close: spacers[4],
            related: spacers[8],
            grouped: spacers[16],
            xxSubSection: spacers[20],
            xSubSection: spacers[24],
            subSection: spacers[32],
            section: spacers[48],
        },
        widthHeight: {
            xxxxxxxxSmall: spacers[1],
            xxxxxxxSmall: spacers[2],
            xxxxxxSmall: spacers[4],
            xxxxxSmall: spacers[6],
            xxxxSmall: spacers[8],
            xxxSmall: spacers[14],
            xxSmall: spacers[16],
            xSmall: spacers[24],
            small: spacers[32],
            base: spacers[40],
            large: spacers[48],
            xLarge: spacers[56],
            xxLarge: spacers[64],
            xxxLarge: spacers[72],
            xxxxLarge: spacers[96],
        },
    },
    borderRadius: {
        noRadius: spacers[0],
        nano: spacers[1],
        micro: spacers[2],
        mini: spacers[4],
        componentInner: spacers[4],
        componentBase: spacers[8],
        sectionInner: spacers[12],
        sectionBase: spacers[24],
        rounded: spacers[999],
    },
    shadows: {
			surface: {
			elevated: `0px 1px 6px rgba(34, 49, 69, 0.12)`,
			hover: `0px 2px 12px rgba(34, 49, 69, 0.12)`,
			},
			overlay: {
			content: `0px 2px 4px rgba(14, 19, 27, 0.16)`,
			tooltip: `0px 2px 8px rgba(14, 19, 27, 0.12)`,
			drawer: `0px 2px 12px rgba(14, 19, 27, 0.12)`,
			modal: `0px 2px 24px rgba(34, 49, 69, 0.16)`,
			notifications: `0px 2px 24px rgba(34, 49, 69, 0.16)`,
			},
	},
	zIndices: { ...zIndices },
	focus: `0px 0px 0px 1px #5B6770`,
	animation: {
		base: `all 0.2s ease-in-out`,
    },
};          

export const darkTheme: DefaultTheme = {
    ...lightTheme,
    colors: {
        textIcon: {
            inverted: colors.base.white,
            neutral: {
                calmest: colors.gray[900],
                calm: colors.gray[400],
                loud: colors.gray[100],
                bold: colors.gray[50],
            },
            interact: {
                enabled: colors.gray[100],
                hover: colors.green[300],
                active: colors.green[400],
                focus: colors.green[300],
                disabled: colors.gray[500],
            },
            success: {
                calmest: colors.gray[900],
                calm: colors.gray[800],
                loud: colors.gray[600],
                bold: colors.gray[500],
            },
            critical: {
                calmest: colors.red[900],
                calm: colors.red[400],
                loud: colors.red[100],
                bold: colors.red[50],                        
            },        
        },
        bg: {   
            global: colors.base.black,
            overlay: colors.base.blackAlpha,
            transparent: colors.base.whiteAlpha,
            neutral: {
                muted: colors.base.black,
                calmest: colors.gray[900],
                calm: colors.gray[900],
                loud: colors.gray[800],
                loudest: colors.gray[600],
                bold: colors.gray[300],
            },
            interact: {
                green: {
                    enabled: colors.green[300],
                    hover: colors.green[200],
                    active: colors.green[400],
                    focus: colors.green[200],
                    disabled: colors.green[600],
                },
                gray: {
                    enabled: colors.gray[400],
                    hover: colors.gray[300],
                    active: colors.gray[500],
                    focus: colors.gray[300],
                    disabled: colors.gray[600],
                },
                lighWeight: {
                    enabled: colors.gray[900],
                    hover: colors.green[900],
                    active: colors.green[800],
                    focus: colors.green[900],
                    disabled: colors.gray[900],
                    selected: colors.base.black,
                    readOnly: colors.base.black,
                },
            },
            success: {
                calmest: colors.green[900],
                calm: colors.green[800],
                loud: colors.green[600],
                bold: colors.green[500],            
            },
            critical: {
                calmest: colors.red[900],
                calm: colors.red[400],
                loud: colors.red[100],
                loudest: colors.red[400],
                bold: colors.red[500],            
            },
        },
        border: {   
            inverted: colors.base.black,
            transparent: colors.base.whiteAlpha,
            neutral: {
                calmest: colors.gray[800],
                calm: colors.gray[700],
                loud: colors.gray[600],
            },
            interact: {
                enabled: colors.gray[200],
                hover: colors.green[200],
                active: colors.green[400],
                focus: colors.green[200],
                disabled: colors.gray[600],
                readOnly: colors.gray[600],
                complexComponent: colors.gray[900],
            },
            success: {
                calmest: colors.green[900],
                calm: colors.green[800],
                loud: colors.green[600],
                bold: colors.green[500],
            },        
            critical: {
                calmest: colors.red[900],
                calm: colors.red[400],
                loud: colors.red[100],
                loudest: colors.red[400],
                bold: colors.red[50],
            },                    
        },        
    },
};